### ISSUE TITLE
最近3个版本的jar包在linux，emacs环境下使用的时候报错

### ISSUE THREAD

**Issue by a1406** [EmmyLua/EmmyLua-LanguageServer#39]
我一直换到了0.55那个版本才能正常运行。
执行环境是emacs28,  lsp-mode环境下。
相关配置全是默认值。
报错信息如下：

Sep 22, 2022 7:41:36 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)                                                                                at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)                                                                                     at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)                                                                                          at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)                                                                       at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)                                                                               at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)                                                                       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)                                                                                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        ... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.eclipse.lsp4j.InitializeParams.getWorkspaceFolders()"\
 is null
        at com.tang.vscode.LuaLanguageServer.initialize(LuaLanguageServer.kt:56)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 13 more

**Comment by CppCXY** [comment]
依赖库lsp4j的问题, 他认为workspace这个变量不可为空,但实际上是可空的.
另外正在基于RUST重写emmylua语言服务, 所以emmylua ls最近没啥改动.

**Comment by CppCXY** [comment]
新版本已经发布,试试看

**Comment by a1406** [comment]
新版本运行没问题，棒棒哒!
